### ISSUE TITLE
JSONP vs CORS

### ISSUE THREAD

**Issue by seanthepottingshed** [JackHaK/TMF#18]
@PeteHaK 

Would CORS be a safer method of retrieving data from the API ( if the Integration Tier is hosted on a different domain )

**Comment by PeteHaK** [comment]
You shouldn't be going client to server at all - you'd be much better to go server to server. Are you planning to build the API calls in ajax directly from the web pages??

**Comment by seanthepottingshed** [comment]
@PeteHaK 

Excellent idea!

Yep I'm more than happy to make the Vue.JS Component Ajax calls to a local endpoint locally which then fetches data from the Integration Tier API via Guzzle ( cUrl wrapper library ).

**Comment by JackHaK** [comment]
Sean,

 

That’s probably a more manageable model – keen to keep the browsers away from the integration tier otherwise security becomes an issue.

 

Guzzle will work fine otherwise the native PHP in Laravel is pretty straight forward – below the code to call the administrate API:

 

Public function inflate($courseID)

{

  /* $credentials = '(username):(password)'; **/

  $credentials = env('ADMINISTRATE_USER','') . ":" . env('ADMINISTRATE_SECRET','');

  $url = env('ADMINISTRATE_URL','') . '/api/v2/event/courses/' . $courseID;

  $options = array(

    'http' => array(

      'method'  => 'GET',

      'header'=>  "Accept: application/json\r\n" .

                  "Authorization: Basic " . base64_encode($credentials)

    )

  );

  $context  = stream_context_create($options);

  $result = file_get_contents($url, false, $context);

 

Pete

**Comment by seanthepottingshed** [comment]
@JackHaK @PeteHaK 

Agreed, totally my confusion re: `JSONP` from meeting.
